### ISSUE TITLE
Timed out waiting for pipe

### ISSUE THREAD

**Issue by RumbleFrog** [keybase/kbfs#585]
I'm unable to do keybase log send as it's getting permission denied for some reason

My keybase is stuck on this screen: 

![vhfdv5](https://cloud.githubusercontent.com/assets/6960234/21276380/2181d230-c39f-11e6-8660-48786b12fcc9.png)

This started with recent Keybase update

Keybase Version: 1.0.18-20161214181335+e063e25

Here's my log for kbfs: 

This part just keep on repeating. It works after I reinstall Keybase, but after restart, it happens again.

```
2016-12-16T14:46:09.794978 - [DEBU keybase util.go:391] 200 + GetSocket
2016-12-16T14:46:09.794978 - [DEBU keybase util.go:392] 201 - GetSocket -> ok
2016-12-16T14:46:09.794978 - [DEBU keybase socket.go:73] 202 | empty socket wrapper; need a new one
2016-12-16T14:46:10.795145 - [DEBU keybase socket.go:88] 203 | DialSocket -> ERROR: Timed out waiting for pipe '\\.\pipe\kbservice\Users\xxlos\AppData\Local\Keybase\keybased.sock' to come available
2016-12-16T14:46:10.795145 - [WARN kbfs connection.go:354] 204 (CONN CryptoClient ca43726a) Connection: error dialing transport: Timed out waiting for pipe '\\.\pipe\kbservice\Users\xxlos\AppData\Local\Keybase\keybased.sock' to come available
2016-12-16T14:46:10.795145 - [WARN kbfs connection.go:519] 205 CryptoClient: connection error: "Timed out waiting for pipe '\\\\.\\pipe\\kbservice\\Users\\xxlos\\AppData\\Local\\Keybase\\keybased.sock' to come available"; retrying in 35.450236521s
```

**Comment by cjb** [comment]
CC @zanderz

**Comment by RumbleFrog** [comment]
Just a quick note: This started with recent Keybase update, it never happened before.

**Comment by zanderz** [comment]
This update attempted to move the executable install target from `%APPDATA%\Keybase` to `%LOCALAPPDATA%\Keybase`. Are there still .exe files in `%APPDATA%\Keybase` ? 

Does `%APPDATA%\Microsoft\Windows\Start Menu\Programs\Startup\KeybaseStartup.lnk` point to the new location? Can you either post `%LOCALAPPDATA%\Keybase\ keybase.service.log` or encrypt it  to me at https://keybase.io/zanderz ?

**Comment by RumbleFrog** [comment]
There are still .exe files in %APPDATA%\Keybase

The .lnk does point to the new location ('AppData\Local\Keybase\runquiet.exe keybase.exe ctl watchdog2')

And here's my service.log:

```
2016-12-16T15:08:51.522003 - [INFO keybase util_windows.go:114] 001 RemoteSettingsRepairman moving from C:\Users\xxlos\AppData\Roaming\Keybase to C:\Users\xxlos\AppData\Local\Keybase
2016-12-16T15:08:51.522003 - [INFO keybase util_windows.go:141] 002    moving Gui
2016-12-16T15:08:51.924917 - [ERRO keybase util_windows.go:153] 003 RemoteSettingsRepairman error moving C:\Users\xxlos\AppData\Roaming\Keybase\Gui to C:\Users\xxlos\AppData\Local\Keybase\Gui - rename C:\Users\xxlos\AppData\Roaming\Keybase\Gui C:\Users\xxlos\AppData\Local\Keybase\Gui: Access is denied.
2016-12-16T15:08:51.925393 - [DEBU keybase json.go:50] 004 + loading updater config file: C:\Users\xxlos\AppData\Local\Keybase\updater.json
2016-12-16T15:08:51.925393 - [DEBU keybase json.go:78] 005 - successfully loaded updater config file
2016-12-16T15:08:52.025824 - [DEBU keybase globals.go:345] 006 Calling shutdown first time through
2016-12-16T15:08:52.025824 - [DEBU keybase login_state.go:1046] 007 + Account "LoginState - Shutdown"
2016-12-16T15:08:52.025824 - [DEBU keybase login_state.go:959] 008 - LoginState: Leaving request loop
2016-12-16T15:08:52.025824 - [DEBU keybase login_state.go:1048] 009 - Account "LoginState - Shutdown"
2016-12-16T15:08:52.025824 - [DEBU keybase globals.go:402] 00a exiting shutdown code=0; err=<nil>
2016-12-16T15:08:52.025824 - [ERRO keybase standard.go:200] 00b rename C:\Users\xxlos\AppData\Roaming\Keybase\Gui C:\Users\xxlos\AppData\Local\Keybase\Gui: Access is denied.
```

**Comment by zanderz** [comment]
The installation process failed to remove the old executable files first, causing the moving process to fail. Can you please uninstall Keybase, delete the contents of %LOCALAPPDATA%\Keybase, and run the latest installer again?

**Comment by RumbleFrog** [comment]
@zanderz That seem to have done it, thanks 👍

**Comment by RumbleFrog** [comment]
Actually, I take that back, it's occurring again with same error in service log

**Comment by zanderz** [comment]
Oh no. Same thing, executables still in `%APPDATA%\Keybase`? Can you please repeat the uninstall of Keybase, delete the contents of `%LOCALAPPDATA%\Keybase` again, and move the contents of `%ALAPPDATA%\Keybase` to `%LOCALAPPDATA%\Keybase`? Sorry about all the trouble. Would like to see a `keybase log send` on this too.

**Comment by RumbleFrog** [comment]
Alright, now when Keybase launches, it crashes instantly, with no log in either directory at all.

**Comment by RumbleFrog** [comment]
To make things easier, may I download an older build before this update?

**Comment by RumbleFrog** [comment]
Anyone can link me legacy download?

**Comment by RumbleFrog** [comment]
Deleted both folders, reinstalled and rekeyed, seems stable for now.

**Comment by jzila** [comment]
It seems that this issue has been resolved.

**Comment by RumbleFrog** [comment]
Sorry for the extreme late update. But this is still occurring, but it's been on and off.

**Comment by RumbleFrog** [comment]
Latest Log ID: 904526cc6d9447ad82abb81c

**Comment by jzila** [comment]
Thanks, @zanderz: any thoughts? I see some mentions of a revoked key.

**Comment by RumbleFrog** [comment]
Doesn't seem to occur anymore about a year later
