### ISSUE TITLE
Type mismatches in disk_limits_unix.go on freebsd/amd64

### ISSUE THREAD

**Issue by cobaugh** [keybase/kbfs#998]
Found this when trying to build the latest master (8f19a38ad8bb185b215f7a87702af1ac71a0d1af) on FreeBSD 11. Looks like Statfs_T defines Bavail as int64 and Bsize as uint64 on freebsd/amd64.

<pre>$ go version
go version go1.8.1 freebsd/amd64
$ go install
# github.com/keybase/kbfs/libkbfs
../libkbfs/disk_limits_unix.go:27: invalid operation: stat.Bavail * uint64(stat.Bsize) (mismatched types int64 and uint64)
../libkbfs/disk_limits_unix.go:32: cannot use stat.Ffree (type int64) as type uint64 in assignment</pre>

**Comment by strib** [comment]
Thanks @cobaugh, I had no idea!  I wonder how you'd ever have negative available bytes.  Anyway, I put up #999 to fix it.

**Comment by strib** [comment]
Should be fixed now.  @cobaugh can you confirm master compiles for you now, and close this out if it looks ok?  Thanks!

**Comment by cobaugh** [comment]
Yep, it's fixed. Still doesn't build, it's getting stuck on something else, but it's at least progress. Thanks!
